"""
Generate data/vendor_news.js from workflow crawl output.
Usage: python scripts/gen_vendor_news_js.py
"""
import json, os, re

SRC = r"C:\Users\KIM\AppData\Local\Temp\claude\C--Users-KIM-Downloads-miru-election-intel\97e565f8-2a5e-4292-82f8-0a3415000898\tasks\w37ah75yt.output"
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "vendor_news.js")

with open(SRC, encoding="utf-8") as f:
    data = json.load(f)

vendors = {}
for v in data["result"]:
    key = v["vendor"]
    relevant = [i for i in v["items"] if i.get("relevant")]
    vendors[key] = {
        "vendorName": v["vendorName"],
        "newsPageUrl": v["newsPageUrl"],
        "fetchError": v.get("fetchError"),
        "totalRelevant": len(relevant),
        "items": relevant,
    }

js = f"""// Auto-generated by scripts/gen_vendor_news_js.py
// Crawled: 2026-06-25
window.MIRU_VENDOR_NEWS = {json.dumps({"crawled_at": "2026-06-25", "vendors": vendors}, ensure_ascii=False, indent=2)};
"""

with open(OUT, "w", encoding="utf-8") as f:
    f.write(js)

total_items = sum(len(v["items"]) for v in vendors.values())
print(f"Generated {OUT}")
print(f"Vendors: {len(vendors)}, Total relevant items: {total_items}")
for k, v in vendors.items():
    print(f"  {k}: {v['totalRelevant']} items")
